In [2]:
import numpy as np

In [3]:
# mảng (list) trong pyhton
ls=[1.,2,3]
print(ls)

[1.0, 2, 3]


In [4]:
#thư viện numpy sẽ conver thành số thực
np.array(ls)

array([1., 2., 3.])

In [5]:
#đổi kiểu dữ liệu thành float32
np.array(ls, dtype='float32')

array([1., 2., 3.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
               [4,5,6]])
type(a2)

numpy.ndarray

In [8]:
#tương tự data frame np có shapre
#in ra số hàng và cột của mảng
np.shape(a2)

(2, 3)

In [9]:
#xem số chiều của mảng
#a2 có 2 mảng 1 chiều ==> mảng 2 chiều
a2.ndim

2

In [10]:
#xem kiểu dữ liệu của phần từ trong mảng
a2.dtype

dtype('int64')

In [11]:
a2.size

6

Creating Numpy Array from stratch


    zeros, ones, full, arange, linspace

In [12]:
#Mục đích hàm zeros để tạo trước 1 mảng có số hàng, số cột cố định
#bấm tổ hợp Ctrl + Shift + Space để hiển thị gợi ý tham số đầu vào
#Thường kiểu dữ liệu numpy là float, để ép kiểu: dtype = int
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#ép kiểu về int
np.zeros([2,3], dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.ones([2,2])*5

array([[5., 5.],
       [5., 5.]])

In [26]:
#creat an array filled with a linear sequence
#starting at 0, ending at 20, stepping by 2
#this is similar to the built-in range() function

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
#Dùng full để tạo mảng và điền vào số bạn mong muốn
np.full([3,5],9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
#linspace dùng để chia khoảng giữa của 2 số
#ví dụ bắt đầu bằng 1 kết thúc bằng 2 chia ra 3 đoạn
np.linspace(1,2, 3)

array([1. , 1.5, 2. ])

random

In [40]:
#Nhập vào 
np.random.random((4,4))

array([[0.31542835, 0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295]])

In [37]:
#Sử dụng seed (hạt giống) để cố định random
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [ ]:
#Điền vào các tham số sau cho normal
#mean: giá trị trung bình
#standerd deviation: độ lệch chuẩn
#size: 2x2

np.random.normal(2,3,(2,2))

array([[ 0.46758459, -1.54189655],
       [ 1.91545331,  3.28499561]])

In [47]:
x1 = np.random.randint(2,9,(10,10))
print(x1)

[[2 8 5 2 4 6 5 4 3 4]
 [3 6 7 3 8 8 2 7 2 2]
 [2 8 2 3 2 5 8 3 6 3]
 [4 6 2 2 4 7 2 6 6 6]
 [3 8 8 3 6 3 7 3 5 7]
 [3 5 7 5 8 8 3 3 3 8]
 [2 5 2 6 3 6 7 2 5 8]
 [4 3 6 6 6 2 2 4 7 2]
 [8 5 5 6 8 3 6 5 5 5]
 [6 4 3 4 4 3 5 5 6 6]]


Array Indexing & Slicing

In [49]:
x1[0,0], x1[-1,-1]

(np.int32(2), np.int32(6))

Slicing

x[start:stop:step]

In [61]:
x2 = np.random.randint(0,10,(4,4))
print(x2)

[[3 9 5 5]
 [1 7 8 6]
 [4 7 3 5]
 [3 6 4 7]]


In [78]:
#Cắt mảng
x2[1:4,0:4]

array([[1, 7, 8, 6],
       [4, 7, 3, 5],
       [3, 6, 4, 7]], dtype=int32)

In [ ]:
#cắt mảng nhảy cóc
x2[1::3]

array([[1, 7, 8, 6]], dtype=int32)

In [81]:
y1 = np.arange(1,10,1)
print(y1)

[1 2 3 4 5 6 7 8 9]


In [86]:
y1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

! [green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## sorting