In [13]:
import numpy as np

In [14]:
# mảng (list) trong pyhton
ls=[1.,2,3]
print(ls)

[1.0, 2, 3]


In [15]:
#thư viện numpy sẽ conver thành số thực
np.array(ls)

array([1., 2., 3.])

In [16]:
#đổi kiểu dữ liệu thành float32
np.array(ls, dtype='float32')

array([1., 2., 3.], dtype=float32)

In [17]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [18]:
a2 = np.array([[1,2,3],
               [4,5,6]])
type(a2)

numpy.ndarray

In [19]:
#tương tự data frame np có shapre
#in ra số hàng và cột của mảng
np.shape(a2)

(2, 3)

In [20]:
#xem số chiều của mảng
#a2 có 2 mảng 1 chiều ==> mảng 2 chiều
a2.ndim

2

In [21]:
#xem kiểu dữ liệu của phần từ trong mảng
a2.dtype

dtype('int64')

In [22]:
a2.size

6

Creating Numpy Array from stratch


    zeros, ones, full, arange, linspace

In [23]:
#Mục đích hàm zeros để tạo trước 1 mảng có số hàng, số cột cố định
#bấm tổ hợp Ctrl + Shift + Space để hiển thị gợi ý tham số đầu vào
#Thường kiểu dữ liệu numpy là float, để ép kiểu: dtype = int
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
#ép kiểu về int
np.zeros([2,3], dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.ones([2,2])*5

array([[5., 5.],
       [5., 5.]])

In [27]:
#creat an array filled with a linear sequence
#starting at 0, ending at 20, stepping by 2
#this is similar to the built-in range() function

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
#Dùng full để tạo mảng và điền vào số bạn mong muốn
np.full([3,5],9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [29]:
#linspace dùng để chia khoảng giữa của 2 số
#ví dụ bắt đầu bằng 1 kết thúc bằng 2 chia ra 3 đoạn
np.linspace(1,2, 3)

array([1. , 1.5, 2. ])

random

In [30]:
#Nhập vào 
np.random.random((4,4))

array([[0.94808488, 0.84958774, 0.85281033, 0.90701129],
       [0.46255494, 0.8876489 , 0.93275963, 0.5174927 ],
       [0.98042855, 0.88462338, 0.38049702, 0.29527281],
       [0.18504616, 0.02215046, 0.15905324, 0.60772322]])

In [31]:
#Sử dụng seed (hạt giống) để cố định random
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [32]:
#Điền vào các tham số sau cho normal
#mean: giá trị trung bình
#standerd deviation: độ lệch chuẩn
#size: 2x2

np.random.normal(2,3,(2,2))

array([[3.3315897 , 3.00102298],
       [6.48223722, 1.38452521]])

In [33]:
x1 = np.random.randint(2,9,(10,10))
print(x1)

[[8 2 3 3 3 2 4 6 5 8]
 [5 4 6 4 2 2 6 7 7 8]
 [2 6 3 6 3 4 4 2 3 3]
 [3 3 5 8 5 8 4 5 2 8]
 [5 7 6 3 4 6 5 6 8 6]
 [6 5 6 6 6 2 8 6 5 4]
 [7 7 7 2 3 7 3 5 2 7]
 [8 2 3 4 6 4 2 7 5 4]
 [4 7 2 7 3 2 4 4 5 4]
 [5 4 3 4 8 5 8 5 5 4]]


Array Indexing & Slicing

In [34]:
x1[0,0], x1[-1,-1]

(np.int64(8), np.int64(4))

Slicing

x[start:stop:step]

In [35]:
x2 = np.random.randint(0,10,(4,4))
print(x2)

[[3 4 1 2]
 [9 1 4 6]
 [8 2 3 0]
 [0 6 0 6]]


In [36]:
#Cắt mảng
x2[1:4,0:4]

array([[9, 1, 4, 6],
       [8, 2, 3, 0],
       [0, 6, 0, 6]])

In [37]:
#cắt mảng nhảy cóc
x2[1::3]

array([[9, 1, 4, 6]])


reshape & transpose

In [38]:
y1 = np.arange(1,10,1)
print(y1)

[1 2 3 4 5 6 7 8 9]


In [39]:
y1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
r = np.array([1,2,3])
print(r)

[1 2 3]


In [49]:
r.shape

(3,)

In [65]:
r.reshape(1,3)

array([[1, 2, 3]])

In [66]:
r.reshape(1,3).shape

(1, 3)

In [ ]:
#Chuyển hàng thành cột transpose


! [green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## sorting